config/routes.rb
Rails.application.routes.draw do
  get 'users' => 'users#index'
  get 'profile/:username' => 'users#show', as: :user_profile
  devise_for :users
  resources :products
  root 'products#index'
  resources :users, only: [:show] do
        resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :last_name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index

     # @comments = Comment.where(:user_id => current_user.id)
     @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @user = User.find(params[:user_id])
    @comment = @user.comments.create(comment_params)
    redirect_to user_path(@user)
  end



  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @user = User.find(params[:user_id])
    @comment = @user.comments.find(params[:id])
    @comment.destroy
    redirect_to user_path(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :text, :whocomment, :title, :user_id)
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
   before_filter :authenticate_user!, only: [:edit, :update, :destroy, :create]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :description, :pic)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show()
		user = User.find_by_username(params[:username])
		if user
			@user = user
		else
			@user = User.find(params[:id])
		end
	end

	def index()
		redirect_to root_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	 def flash_class(level)
     case level
     when :notice then "alert alert-info"
     when :success then "alert alert-success"
     when :error then "alert alert-error"
     when :alert then "alert alert-error"
     end
 end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/comments/_form.html.erb
    <%= form_for([@user, @user.comments.build]) do |f| %>
      <% if @user.comments.build.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.comments.build.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
          <% @user.comments.build.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.hidden_field :whocomment, :value => current_user.username %>
      <%= f.hidden_field :title, :value => @user.username %>

      <div class="field form-group">
        <%= f.text_area :text, class: 'form-control', :placeholder => 'Type your comment here' %>
      </div>

      <div class="actions">
        <%= f.submit "Send comment", class: "btn btn-default" %>
      </div>
    <% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>References</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.text %></td>
        <td><%= comment.references %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>References:</strong>
  <%= @comment.references %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "GAM Store", root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      	<% if user_signed_in? %>
        <li><%= link_to "Profile", user_profile_path(:username => current_user.username) %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <% flash.each do |key, value| %>
    <div class="alert alert-success alert-dismissable">
  		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  		<%= value %>
	</div>
  <% end %>

<%= yield %>
</div>
</body>
</html>

app/views/products/_form.html.erb
<div class = 'row'>
<div class="col-lg-4 col-md-6 col-sm-8 col-xs-12 col-lg-offset-4 col-md-offset-3 col-sm-offset-2" >
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :pic %><br>
    <%= f.text_field :pic, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Send", class: "btn btn-default" %>
  </div>
<% end %>
</div></div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<div class="row">
	<div class="col-lg-4 col-md-6 col-sm-8 col-xs-12 col-lg-offset-4 col-md-offset-3 col-sm-offset-2">
<%= link_to 'Product Detail', @product %> |
<%= link_to '< Back', products_path %>
	</div>
</div>

app/views/products/index.html.erb
<h1 class = "">Listing Products</h1>
<% if @products.count > 0 %>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">All Products</div>

  <!-- Table -->
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Description</th>
        <th>Pic</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.title %></td>
          <td><%= product.price %></td>
          <td><%= product.description %></td>
          <td><%= product.pic %></td>
          <td><%= link_to product do %> 
         <span class ="glyphicon glyphicon-search" ></span>
          <% end %></td>
          <td><%= link_to edit_product_path(product) do %> 
         <span class ="glyphicon glyphicon-pencil" ></span>
          <% end %></td>
          <td><%= link_to product, method: :delete, data: { confirm: 'Are you sure?' } do %> 
         <span class ="glyphicon glyphicon-trash" ></span>
          <% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
 <%= link_to 'New Product', new_product_path, class: "btn btn-default pull-right" %>
  </div>
</div>

<% else %>
  <p>There's no products yet. Add one to the list :) </p>
  <%= link_to 'New Product', new_product_path, class: "btn btn-default" %>
<% end %>

<br>

app/views/products/new.html.erb
<h1 class = "text-center">New Product</h1>

<%= render 'form' %>
<div class = 'row'>
<div class="col-lg-4 col-md-6 col-sm-8 col-xs-12 col-lg-offset-4 col-md-offset-3 col-sm-offset-2" >
<%= link_to '< Back', products_path %>
</div></div>

app/views/products/show.html.erb
<h2 class = "text-center"> Product Detail</h2>
<div class="row">
	<div class="col-xs-12 col-lg-8 col-md-8 col-sm-8 col-lg-offset-2">
	<div class="panel panel-success"> 
<div class="panel-heading">Product</div> 
	  <div class="panel-body">
    	<ul class="list-group">
		  <li class="list-group-item"><strong>Title: </strong><%= @product.title %></li>
		  <li class="list-group-item"><strong>Price: </strong><%= @product.price %> </li>
		  <li class="list-group-item"><strong>Description: </strong><%= @product.description %> </li>
		</ul>
  	</div>
</div>

<%= link_to 'Edit Product', edit_product_path(@product), class: "btn btn-default" %> |
<%= link_to '< Back', products_path %>
	</div>
</div>

app/views/users/show.html.erb
<h2><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= @user.username%> </h2>
<div class="panel panel-success"> 
	<div class="panel-heading">About</div> 
 	  <div class="panel-body">
	    	<ul class="list-group">
			  <li class="list-group-item"><strong>Name: </strong><%= @user.name %> <%= @user.last_name %></li>
			  <li class="list-group-item"><strong>Email: </strong><%= @user.email %> </li>
			 </ul>
	  </div>
</div>
<% if user_signed_in? %>
<div class="row">
	<div class="col-xs-12 col-lg-4 col-md-4 col-sm-6">
		<h4> Add a comment :)</h4>
		<%= render 'comments/form' %>
	</div>
</div>
<% end %>
<div class="row">
	<div class="col-lg-6">
		<h4>RECENT COMMENTS</h4>
		<% all_comments = @user.comments.order("created_at DESC") %>
		<% if all_comments.count > 0 %>
		<% all_comments.each do |comment| %>
			<div class="panel panel-default">
			  <div class="panel-heading">
			  <% if comment.whocomment == "Anonnymus" %>
				<strong>Anonnymus</strong> 
			  <% else %>
			    <strong><%= link_to comment.whocomment, user_profile_path(comment.whocomment) %></strong> 
				<% end %>
			    commented 

			    <%= link_to [comment.user, comment],
					         method: :delete,
					         data: { confirm: 'Are you sure?' }, class: "pull-right" do %> 
				<span class ="glyphicon glyphicon-trash" ></span>
				<% end %>
			  </div>
			  <div class="panel-body">
			    <%= comment.text %>
			  </div>
			</div>
		<% end %>
		<% else %>
			<p>There's no comments yet. Be the first one!</p>
		<% end %>
	</div>
</div>